### ISSUE TITLE
Uploading cookbook to chef server: libraries/helper.rb has a ruby syntax error

### ISSUE THREAD

**Issue by joelmoss** [reset/libarchive-cookbook#5]
Uploading libarchive to my open source chef server using Berkshelf results in this error:

```
E, [2014-08-18T13:53:43.107972 #3237] ERROR -- : Cookbook file libraries/helper.rb has a ruby syntax error:
E, [2014-08-18T13:53:43.108099 #3237] ERROR -- : rbenv: version `2.1.1' is not installed
E, [2014-08-18T13:53:43.108142 #3237] ERROR -- : rbenv: version `2.1.1' is not installed
E, [2014-08-18T13:53:43.110971 #3237] ERROR -- : Ridley::Errors::CookbookSyntaxError: Invalid ruby files in cookbook: libarchive (0.4.0).
E, [2014-08-18T13:53:43.112508 #3237] ERROR -- : /Users/joelmoss/.chefdk/gem/ruby/2.1.0/gems/ridley-4.0.0/lib/ridley/chef/cookbook.rb:198:in `validate'
/Users/joelmoss/.chefdk/gem/ruby/2.1.0/gems/ridley-4.0.0/lib/ridley/resources/cookbook_resource.rb:197:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/calls.rb:26:in `public_send'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/calls.rb:26:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/calls.rb:63:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/cell.rb:60:in `block in invoke'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/cell.rb:71:in `block in task'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/actor.rb:369:in `block in task'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/tasks.rb:55:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/tasks/task_thread.rb:21:in `block in create'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/thread_handle.rb:13:in `block in initialize'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/actor_system.rb:32:in `block in get_thread'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/internal_pool.rb:99:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/internal_pool.rb:99:in `block in create'
(celluloid):0:in `remote procedure call'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/calls.rb:92:in `value'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0.pre2/lib/celluloid/proxies/sync_proxy.rb:33:in `method_missing'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:54:in `block (2 levels) in upload'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:50:in `each'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:50:in `block in upload'
/Users/joelmoss/.chefdk/gem/ruby/2.1.0/gems/ridley-4.0.0/lib/ridley/client.rb:36:in `open'
/Users/joelmoss/.chefdk/gem/ruby/2.1.0/gems/ridley-4.0.0/lib/ridley.rb:51:in `open'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf.rb:157:in `ridley_connection'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:49:in `upload'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/uploader.rb:36:in `run'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:542:in `upload'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:208:in `upload'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
/opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
/opt/chefdk/bin/berks:37:in `load'
/opt/chefdk/bin/berks:37:in `<main>'
There was an error connecting to the Chef Server
```

Any ideas?

**Comment by reset** [comment]
There's no longer a .ruby-version file in the cookbook root so this should no longer be an issue
